### ISSUE TITLE
Autocomplete Flag Parsing Order

### ISSUE THREAD

**Issue by cmprmsd** [brianstrauch/cobra-shell#2]
Currently flags do show up like this:
![image](https://user-images.githubusercontent.com/73472903/164946710-20023ae5-afea-43b5-aaa2-74e85fd5384c.png)

However, it might be a good idea to display all `--flags` first and after them the `-f`(lags).
Another solution would be to show only the long version or both in one line as the description has to be the same and on autocomplete insert the long one as this is the most descriptive. This might need some conditional logic I guess if there are cases with short but no long flags or the other way round.

**Comment by brianstrauch** [comment]
Good idea! For simplicity's sake, I think it's best just to hide the shorthand flags. It doesn't look like it's possible to create a shorthand-only flag with Cobra.

**Comment by brianstrauch** [comment]
Thanks for reporting! Added in [v0.3.0](https://github.com/brianstrauch/cobra-shell/tree/v0.3.0)

**Comment by cmprmsd** [comment]
Great solution and works mostly as expected. :+1: 
It's also nice that the auto completion still respects shorthand flags if one is used to them.
The following screenshot shows that --base64 is hidden, because the shorthand flag of it was used already. 

![image](https://user-images.githubusercontent.com/73472903/165630609-f90320e1-f10d-4926-af72-36449d1978c8.png)

One minor glitch I noticed is when you use backspace after completing a word sometimes it still gets removed from the suggestions as in this case --gzip:
![image](https://user-images.githubusercontent.com/73472903/165631735-0b051f8d-4727-4399-8331-ad77146efc21.png)

What do you think of showing the completion like the following?
`--base64 (-b) | enable base64`
This way you would keep the information about each shorthand flag without having additional lines. My app is not very complex yet but I think this might be a good idea. :D
